### PR TITLE
Implement color palette and adjust color references

### PR DESCRIPTION
**Pull request by milolucero**
### Changes
- Added a color palette that is referenced both as CSS variables as in Tailwind.
- Changed previous color references to use new color palette.

### Known issues
- Minor: Tailwind won't allow to make a different color with the same name for a background as for text, preventing from creating a text-dark-hover color.

### CODE REVIEW

**Comment by bandrson** [comment]
Excellent work. I have commits written for the following changes, but I'll wait to push them until I hear your thoughts.

### Proposed Changes

- Rename `primary` to `brand` in the context of the color palette. This name feels clearer to me
- Add `light-font` and `dark-font` Tailwind classes to fix the issue you mentioned
- Fix some missed classes in components

**Comment by milolucero** [comment]
> Excellent work. I have commits written for the following changes, but I'll wait to push them until I hear your thoughts.
> 
> ### Proposed Changes
> * Rename `primary` to `brand` in the context of the color palette. This name feels clearer to me
> * Add `light-font` and `dark-font` Tailwind color classes to fix the issue you mentioned
> * Fix some missed classes in components

Thank you. The `light-font` and `dark-font` classes sounds like a good solution for the issue. Thanks for fixing the missing classes! 

The reason why I think `primary` is a good naming option is because in design a brand will usually have up to three "brand colors", which are usually referenced as primary, secondary, and tertiary in design jargon.

While the BBA brand currently only makes use of one brand color, setting this color name as `primary` opens the possiblity of eventually adding a `secondary` and `tertiary` color in the case of a redesign of the brand at any point in the future.

Most frameworks such as [Bootstrap](https://getbootstrap.com/docs/5.0/utilities/colors/) and [Google MD](https://www.material.io/design/color/the-color-system.html#color-usage-and-palettes) also make use of that naming convention, which would keep us more consistent to standards.

Let me know your thoughts and feel free to push your proposed changes!

**Comment by bandrson** [comment]
> > Excellent work. I have commits written for the following changes, but I'll wait to push them until I hear your thoughts.
> > ### Proposed Changes
> > 
> > * Rename `primary` to `brand` in the context of the color palette. This name feels clearer to me
> > * Add `light-font` and `dark-font` Tailwind color classes to fix the issue you mentioned
> > * Fix some missed classes in components
> 
> Thank you. The `light-font` and `dark-font` classes sounds like a good solution for the issue. Thanks for fixing the missing classes!
> 
> The reason why I think `primary` is a good naming option is because in design a brand will usually have up to three "brand colors", which are usually referenced as primary, secondary, and tertiary in design jargon.
> 
> While the BBA brand currently only makes use of one brand color, setting this color name as `primary` opens the possiblity of eventually adding a `secondary` and `tertiary` color in the case of a redesign of the brand at any point in the future.
> 
> Most frameworks such as [Bootstrap](https://getbootstrap.com/docs/5.0/utilities/colors/) and [Google MD](https://www.material.io/design/color/the-color-system.html#color-usage-and-palettes) also make use of that naming convention, which would keep us more consistent to standards.
> 
> Let me know your thoughts and feel free to push your proposed changes!

Ah, I was not aware of that naming convention for colors. In that case, I agree with keeping it as-is to remain consistent with common standards.

**Comment by bandrson** [comment]
I've pushed my commits. Feel free to merge if everything looks good!

**Pull request merged**
